#开发环境
breakpoint:
  upload:
    dir: D:/data0/uploads/
    #1024*1024=1048576 5M=5242880
    chunkSize: 5242880

spring:
  http:
  servlet:
    multipart:
      # 文件的最大值
      max-file-size: 1024MB
      # 单次请求最大的值
      max-request-size: 10MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tmp_db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 120000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      seGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# mybatis的mapper文件存放的位置，java和mapper.xml不在同一位置时候起作用
mybatis:
  type-aliases-package: win.pangniu.learn.pojo
  mapper-locations: classpath:/win/pangniu/learn/mapper/*.xml

# mybatis-plus的配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false
